name: Sync
'on':
  schedule:
    - cron: '0 3 * * *'
  push:
    branches:
      - main
jobs:
  files:
    name: Files
    runs-on: ubuntu-latest
    steps:
      - uses: adrianjost/files-sync-action@v1
        with:
          GITHUB_TOKEN: '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'
          FILE_PATTERNS: |
            ^LICENSE\.md$
          TARGET_REPOS: |
            sampere15/test-backend-master
